package com.techsure.strange.regex;

import org.junit.Test;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * @author zhoujian
 * @Date 2018/10/25 15:10
 */
public class RegexTest {
	private static final Logger logger = LoggerFactory.getLogger(RegexTest.class);

	@Test
	public void testReplace() {
		String str = "\n" +
				"<div><span></span>哈哈哈哈哈</div>\n" +
				"<div><br></div><hr style=\"width: 210px; height: 1px;\" color=\"#b5c4df\" size=\"1\" align=\"left\">\n" +
				"<div><span><div style=\"MARGIN: 10px; FONT-FAMILY: verdana; FONT-SIZE: 10pt\"><span style=\"font-family: Verdana;\">周健&nbsp;</span><br style=\"font-family: 'Lucida Grande', 'Lucida Sans Unicode', sans-serif !important;\"><span style=\"font-family: Verdana;\">深圳市赞悦科技有限公司&nbsp;</span><br style=\"font-family: 'Lucida Grande', 'Lucida Sans Unicode', sans-serif !important;\"><span style=\"font-family: Verdana;\">手机:15302610285&nbsp;</span><br style=\"font-family: 'Lucida Grande', 'Lucida Sans Unicode', sans-serif !important;\"><span style=\"font-family: Verdana;\">总机：4008160890&nbsp;</span><br style=\"font-family: 'Lucida Grande', 'Lucida Sans Unicode', sans-serif !important;\"><span style=\"font-family: Verdana;\">邮箱：zhoujian@techsure.com.cn</span><br style=\"font-family: 'Lucida Grande', 'Lucida Sans Unicode', sans-serif !important;\"><span style=\"font-family: Verdana;\">地址：深圳市南山区科技园科苑路讯美科技广场2号楼901室</span></div><div style=\"MARGIN: 10px; FONT-FAMILY: verdana; FONT-SIZE: 10pt\"><a href=\"http://www.techsure.com.cn/\" title=\"http://www.techsure.com.cn\" target=\"_blank\" style=\"text-decoration: none; color: rgb(19, 109, 186); -webkit-user-drag: none; font-family: 'Lucida Grande', 'Lucida Sans Unicode', sans-serif;\"><img src=\"/balantflow//file/getFile.do?belong=ALERT&fileid=183\" class=\"no_selection_effect\" style=\"max-width: 100%; height: auto !important;\"></a></div></span></div>\n" +
				"<blockquote style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0.5em;\"><div>&nbsp;</div><div style=\"border:none;border-top:solid #B5C4DF 1.0pt;padding:3.0pt 0cm 0cm 0cm\"><div style=\"PADDING-RIGHT: 8px; PADDING-LEFT: 8px; FONT-SIZE: 12px;FONT-FAMILY:tahoma;COLOR:#000000; BACKGROUND: #efefef; PADDING-BOTTOM: 8px; PADDING-TOP: 8px\"><div><b>发件人：</b>&nbsp;<a href=\"mailto:zhoujian@techsure.com.cn\">zhoujian@techsure.com.cn</a></div><div><b>发送时间：</b>&nbsp;2018-10-25&nbsp;15:07</div><div><b>收件人：</b>&nbsp;<a href=\"mailto:zhoujian@techsure.com.cn\">周健</a></div><div><b>主题：</b>&nbsp;Re: Re: 20181025-1邮件测试</div></div></div><div><div class=\"FoxDiv20181025150826646622\">\n" +
				"<div><span></span>啛啛喳喳</div>\n" +
				"<div><br></div><hr style=\"width: 210px; height: 1px;\" color=\"#b5c4df\" size=\"1\" align=\"left\">\n" +
				"<div><span><div style=\"MARGIN: 10px; FONT-FAMILY: verdana; FONT-SIZE: 10pt\"><span style=\"font-family: Verdana;\">周健&nbsp;</span><br style=\"font-family: 'Lucida Grande', 'Lucida Sans Unicode', sans-serif !important;\"><span style=\"font-family: Verdana;\">深圳市赞悦科技有限公司&nbsp;</span><br style=\"font-family: 'Lucida Grande', 'Lucida Sans Unicode', sans-serif !important;\"><span style=\"font-family: Verdana;\">手机:15302610285&nbsp;</span><br style=\"font-family: 'Lucida Grande', 'Lucida Sans Unicode', sans-serif !important;\"><span style=\"font-family: Verdana;\">总机：4008160890&nbsp;</span><br style=\"font-family: 'Lucida Grande', 'Lucida Sans Unicode', sans-serif !important;\"><span style=\"font-family: Verdana;\">邮箱：zhoujian@techsure.com.cn</span><br style=\"font-family: 'Lucida Grande', 'Lucida Sans Unicode', sans-serif !important;\"><span style=\"font-family: Verdana;\">地址：深圳市南山区科技园科苑路讯美科技广场2号楼901室</span></div><div style=\"MARGIN: 10px; FONT-FAMILY: verdana; FONT-SIZE: 10pt\"><a href=\"http://www.techsure.com.cn/\" title=\"http://www.techsure.com.cn\" target=\"_blank\" style=\"text-decoration: none; color: rgb(19, 109, 186); -webkit-user-drag: none; font-family: 'Lucida Grande', 'Lucida Sans Unicode', sans-serif;\"><img src=\"/balantflow//file/getFile.do?belong=ALERT&fileid=184\" class=\"no_selection_effect\" style=\"max-width: 100%; height: auto !important;\"></a></div></span></div>\n" +
				"<blockquote style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0.5em;\"><div>&nbsp;</div><div style=\"border:none;border-top:solid #B5C4DF 1.0pt;padding:3.0pt 0cm 0cm 0cm\"><div style=\"PADDING-RIGHT: 8px; PADDING-LEFT: 8px; FONT-SIZE: 12px;FONT-FAMILY:tahoma;COLOR:#000000; BACKGROUND: #efefef; PADDING-BOTTOM: 8px; PADDING-TOP: 8px\"><div><b>发件人：</b>&nbsp;<a href=\"mailto:zhoujian@techsure.com.cn\">zhoujian@techsure.com.cn</a></div><div><b>发送时间：</b>&nbsp;2018-10-25&nbsp;15:01</div><div><b>收件人：</b>&nbsp;<a href=\"mailto:zhoujian@techsure.com.cn\">周健</a></div><div><b>主题：</b>&nbsp;Re: 回复: 20181025-1邮件测试</div></div></div><div><div class=\"FoxDiv20181025150403148576\">\n" +
				"<div><span></span>再次回复</div>\n" +
				"<div><br></div><hr style=\"width: 210px; height: 1px;\" color=\"#b5c4df\" size=\"1\" align=\"left\">\n" +
				"<div><span><div style=\"MARGIN: 10px; FONT-FAMILY: verdana; FONT-SIZE: 10pt\"><span style=\"font-family: Verdana;\">周健&nbsp;</span><br style=\"font-family: 'Lucida Grande', 'Lucida Sans Unicode', sans-serif !important;\"><span style=\"font-family: Verdana;\">深圳市赞悦科技有限公司&nbsp;</span><br style=\"font-family: 'Lucida Grande', 'Lucida Sans Unicode', sans-serif !important;\"><span style=\"font-family: Verdana;\">手机:15302610285&nbsp;</span><br style=\"font-family: 'Lucida Grande', 'Lucida Sans Unicode', sans-serif !important;\"><span style=\"font-family: Verdana;\">总机：4008160890&nbsp;</span><br style=\"font-family: 'Lucida Grande', 'Lucida Sans Unicode', sans-serif !important;\"><span style=\"font-family: Verdana;\">邮箱：zhoujian@techsure.com.cn</span><br style=\"font-family: 'Lucida Grande', 'Lucida Sans Unicode', sans-serif !important;\"><span style=\"font-family: Verdana;\">地址：深圳市南山区科技园科苑路讯美科技广场2号楼901室</span></div><div style=\"MARGIN: 10px; FONT-FAMILY: verdana; FONT-SIZE: 10pt\"><a href=\"http://www.techsure.com.cn/\" title=\"http://www.techsure.com.cn\" target=\"_blank\" style=\"text-decoration: none; color: rgb(19, 109, 186); -webkit-user-drag: none; font-family: 'Lucida Grande', 'Lucida Sans Unicode', sans-serif;\"><img src=\"/balantflow//file/getFile.do?belong=ALERT&fileid=185\" class=\"no_selection_effect\" style=\"max-width: 100%; height: auto !important;\"></a></div></span></div>\n" +
				"<blockquote style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0.5em;\"><div>&nbsp;</div><div style=\"border:none;border-top:solid #B5C4DF 1.0pt;padding:3.0pt 0cm 0cm 0cm\"><div style=\"PADDING-RIGHT: 8px; PADDING-LEFT: 8px; FONT-SIZE: 12px;FONT-FAMILY:tahoma;COLOR:#000000; BACKGROUND: #efefef; PADDING-BOTTOM: 8px; PADDING-TOP: 8px\"><div><b>发件人：</b>&nbsp;<a href=\"mailto:zhoujian@techsure.com.cn\">zhoujian@techsure.com.cn</a></div><div><b>发送时间：</b>&nbsp;2018-10-25&nbsp;14:59</div><div><b>收件人：</b>&nbsp;<a href=\"mailto:zhoujian@techsure.com.cn\">周健</a></div><div><b>主题：</b>&nbsp;回复: 20181025-1邮件测试</div></div></div><div><div class=\"FoxDiv20181025150108606873\">\n" +
				"<div><span></span>回复内容</div>\n" +
				"<div><br></div><hr style=\"width: 210px; height: 1px;\" color=\"#b5c4df\" size=\"1\" align=\"left\">\n" +
				"<div><span><div style=\"MARGIN: 10px; FONT-FAMILY: verdana; FONT-SIZE: 10pt\"><span style=\"font-family: Verdana;\">周健&nbsp;</span><br style=\"font-family: 'Lucida Grande', 'Lucida Sans Unicode', sans-serif !important;\"><span style=\"font-family: Verdana;\">深圳市赞悦科技有限公司&nbsp;</span><br style=\"font-family: 'Lucida Grande', 'Lucida Sans Unicode', sans-serif !important;\"><span style=\"font-family: Verdana;\">手机:15302610285&nbsp;</span><br style=\"font-family: 'Lucida Grande', 'Lucida Sans Unicode', sans-serif !important;\"><span style=\"font-family: Verdana;\">总机：4008160890&nbsp;</span><br style=\"font-family: 'Lucida Grande', 'Lucida Sans Unicode', sans-serif !important;\"><span style=\"font-family: Verdana;\">邮箱：zhoujian@techsure.com.cn</span><br style=\"font-family: 'Lucida Grande', 'Lucida Sans Unicode', sans-serif !important;\"><span style=\"font-family: Verdana;\">地址：深圳市南山区科技园科苑路讯美科技广场2号楼901室</span></div><div style=\"MARGIN: 10px; FONT-FAMILY: verdana; FONT-SIZE: 10pt\"><a href=\"http://www.techsure.com.cn/\" title=\"http://www.techsure.com.cn\" target=\"_blank\" style=\"text-decoration: none; color: rgb(19, 109, 186); -webkit-user-drag: none; font-family: 'Lucida Grande', 'Lucida Sans Unicode', sans-serif;\"><img src=\"/balantflow//file/getFile.do?belong=ALERT&fileid=186\" class=\"no_selection_effect\" style=\"max-width: 100%; height: auto !important;\"></a></div></span></div>\n" +
				"<blockquote style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0.5em;\"><div>&nbsp;</div><div style=\"border:none;border-top:solid #B5C4DF 1.0pt;padding:3.0pt 0cm 0cm 0cm\"><div style=\"PADDING-RIGHT: 8px; PADDING-LEFT: 8px; FONT-SIZE: 12px;FONT-FAMILY:tahoma;COLOR:#000000; BACKGROUND: #efefef; PADDING-BOTTOM: 8px; PADDING-TOP: 8px\"><div><b>发件人：</b>&nbsp;<a href=\"mailto:zhoujian@techsure.com.cn\">zhoujian@techsure.com.cn</a></div><div><b>发送时间：</b>&nbsp;2018-10-25&nbsp;14:56</div><div><b>收件人：</b>&nbsp;<a href=\"mailto:zhoujian@techsure.com.cn\">zhoujian</a></div><div><b>主题：</b>&nbsp;20181025-1邮件测试</div></div></div><div><div class=\"FoxDiv20181025145705897799\">\n" +
				"<div><span></span>邮件正文内容</div>\n" +
				"<div><br></div><hr style=\"width: 210px; height: 1px;\" color=\"#b5c4df\" size=\"1\" align=\"left\">\n" +
				"<div><span><div style=\"MARGIN: 10px; FONT-FAMILY: verdana; FONT-SIZE: 10pt\"><span style=\"font-family: Verdana;\">周健&nbsp;</span><br style=\"font-family: 'Lucida Grande', 'Lucida Sans Unicode', sans-serif !important;\"><span style=\"font-family: Verdana;\">深圳市赞悦科技有限公司&nbsp;</span><br style=\"font-family: 'Lucida Grande', 'Lucida Sans Unicode', sans-serif !important;\"><span style=\"font-family: Verdana;\">手机:15302610285&nbsp;</span><br style=\"font-family: 'Lucida Grande', 'Lucida Sans Unicode', sans-serif !important;\"><span style=\"font-family: Verdana;\">总机：4008160890&nbsp;</span><br style=\"font-family: 'Lucida Grande', 'Lucida Sans Unicode', sans-serif !important;\"><span style=\"font-family: Verdana;\">邮箱：zhoujian@techsure.com.cn</span><br style=\"font-family: 'Lucida Grande', 'Lucida Sans Unicode', sans-serif !important;\"><span style=\"font-family: Verdana;\">地址：深圳市南山区科技园科苑路讯美科技广场2号楼901室</span></div><div style=\"MARGIN: 10px; FONT-FAMILY: verdana; FONT-SIZE: 10pt\"><a href=\"http://www.techsure.com.cn/\" title=\"http://www.techsure.com.cn\" target=\"_blank\" style=\"text-decoration: none; color: rgb(19, 109, 186); -webkit-user-drag: none; font-family: 'Lucida Grande', 'Lucida Sans Unicode', sans-serif;\"><img src=\"/balantflow//file/getFile.do?belong=ALERT&fileid=187\" class=\"no_selection_effect\" style=\"max-width: 100%; height: auto !important;\"></a></div></span></div>\n" +
				"</div></div></blockquote>\n" +
				"</div></div></blockquote>\n" +
				"</div></div></blockquote>\n" +
				"</div></div></blockquote>\n";

		String str2 = "test<hr id=\"FMSigSeperator\"test<hr id=\"FMSigSeperator\"test";
		String replyStr = "<hr";
		Pattern replyPat = Pattern.compile(replyStr + ".*",Pattern.DOTALL);
		Matcher m = replyPat.matcher(str);
		//str = m.replaceAll("");
		str = m.replaceAll("");
		logger.info(str);
	}
}
